cursor #1b1e2b
cursor_text_color #4b556a

foreground            #1b1e2b
background            #fdfdff
selection_foreground  #f8fbff
selection_background  #a78bfa
url_color             #2f7fd6

color0   #1a1b26
color1   #cb0c45
color2   #00a015
color3   #fff100
color4   #2880e0
color5   #bfddff
color6   #2f7fd6
color7   #38393b
color8   #aeb2b5
color9   #ff3873
color10  #21eb3c
color11  #fff100
color12  #2288f6
color13  #bfddff
color14  #9bcbff
color15  #f7faff
