-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(2f7fd6)",
			inactive_border = "rgb(9a9dab)",
		},
	},
	group = {
		col = {
			border_active = "rgb(2f7fd6)",
			border_inactive = "rgb(9a9dab)",
			border_locked_active = "rgb(ff5c7a)",
			border_locked_inactive = "rgb(9a9dab)",
		},
		groupbar = {
			col = {
				active = "rgb(2f7fd6)",
				inactive = "rgb(9a9dab)",
				locked_active = "rgb(ff5c7a)",
				locked_inactive = "rgb(9a9dab)",
			},
		},
	},
})
