{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix # regenerated by install.sh, placeholder until then
    ./disko.nix
    ../../modules/desktop.nix
    ../../modules/greeter.nix # greetd + tuigreet session picker
    ../../modules/niri.nix # niri compositor (DMS session)
    ../../modules/vfio.nix # 3080 passthrough + libvirt + Looking Glass (replaced nvidia.nix)
    ../../modules/comfyui-vm.nix # host plumbing for the ComfyUI sandbox VM (guest: comfyui-guest.nix)
    ../../modules/steam.nix # steam + gamemode; games live on /storage/games
  ];

  networking.hostName = "nix";
  networking.networkmanager.enable = true;

  # ── Boot ────────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.consoleMode = "max";
  boot.loader.efi.canTouchEfiVariables = true;
  # systemd in the initrd: needed for a clean graphical LUKS prompt.
  boot.initrd.systemd.enable = true;
  # Plymouth = the fancy boot splash / LUKS unlock screen (what Bluefin has).
  boot.plymouth.enable = true;
  boot.kernelParams = [ "quiet" "splash" ];
  # LUKS devices and filesystems come from disko.nix; no hardcoded UUIDs here.

  # Unlock the storage SSD after root is up, using the keyfile install.sh
  # placed at /etc/cryptkey. disko's initrdUnlock=false only *skips* the
  # initrd entry — verified it emits no crypttab — so we provide it.
  # nofail on both ends: a dead/absent storage drive must not block boot.
  environment.etc.crypttab.text = ''
    cryptstorage /dev/disk/by-partlabel/disk-storage-luks /etc/cryptkey discard,nofail
  '';

  # ── Swap ────────────────────────────────────────────────────────────────
  zramSwap.enable = true; # compressed RAM swap, no disk swap / no hibernation

  # ── Locale / time ───────────────────────────────────────────────────────
  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Nix itself ──────────────────────────────────────────────────────────
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.trusted-users = [ "root" "@wheel" ];
  nixpkgs.config.allowUnfree = true;

  # ── User ────────────────────────────────────────────────────────────────
  users.users.z = {
    isNormalUser = true;
    description = "z";
    shell = pkgs.fish;
    extraGroups = [ "networkmanager" "wheel" "audio" "input" ];
    # Personal apps live in home/z.nix (home-manager), not here.
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    users.z = import ../../home/z.nix;
    # home/z.nix needs `inputs` to patch the caelestia-shell package
    extraSpecialArgs = { inherit inputs; };
    # programs.caelestia.* / programs.dank-material-shell.* options (home/z.nix)
    sharedModules = [
      inputs.caelestia-shell.homeManagerModules.default
      inputs.dms.homeModules.dank-material-shell
      # NOT inputs.dms.homeModules.niri — that one assumes sodiboo's
      # niri-flake (programs.niri.settings); our niri config is a plain
      # live-editable config.kdl like the hypr dotfiles.
    ];
    # if a real file is in the way of a managed one, back it up instead
    # of failing the whole activation
    backupFileExtension = "hm-bak";
  };

  # ── System-level programs / services ────────────────────────────────────
  programs.fish.enable = true;
  programs.neovim.enable = true;
  programs.neovim.defaultEditor = true;
  programs.direnv.enable = true;

  # 1Password needs to be system-level for polkit + the SSH agent to work.
  programs._1password.enable = true;
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = [ "z" ];
  };

  # Helps random downloaded binaries and editor tooling run on NixOS.
  programs.nix-ld.enable = true;
  services.envfs.enable = true;

  services.flatpak.enable = true;
  services.udisks2.enable = true;
  services.fstrim.enable = true; # periodic TRIM for both SSDs

  # ── Mullvad VPN ─────────────────────────────────────────────────────────
  # Must be system-level: the app talks to mullvad-daemon (a root systemd
  # service that owns the firewall rules / kill switch). mullvad-vpn is the
  # full GUI app + CLI; the service installs it system-wide, so nothing is
  # needed in home/z.nix.
  services.mullvad-vpn = {
    enable = true;
    package = pkgs.mullvad-vpn;
  };

  # `nh os switch` with no args after this
  programs.nh = {
    enable = true;
    flake = "/home/z/nixos";
  };

  # ── Audio: pipewire (replaces the old pulseaudio setup) ─────────────────
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── Bluetooth ───────────────────────────────────────────────────────────
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  # ── System packages (CLI + infrastructure only) ─────────────────────────
  environment.systemPackages = with pkgs; [
    git
    wget
    curl
    unzip
    killall
    tldr
    zoxide
    fzf
    bat
    eza
    btop
    fastfetch
    oh-my-posh
    wl-clipboard
    nix-search-cli
    ntfs3g
  ];

  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono # nerdfonts was split into per-font packages
    inter # "Inter Variable" — DMS default UI font
    fira-code # DMS default monospace font
  ];

  # ── Deferred until after the migration settles ──────────────────────────
  # (libvirtd + virt-manager now live in modules/vfio.nix)
  # hardware.openrazer.enable = true;   # + polychromatic in home packages
  # networking.hosts entries for the work VMs: re-add from the old config
  # (kept out of this repo) once libvirtd is confirmed working.

  system.stateVersion = "26.05"; # fresh install on 26.05; do not change later
}
